[tasks.clean]
command = "rm"
args = ["-rf", "target", "pkg"]

[tasks.prep]
command = "mkdir"
args = ["pkg"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.rename-linux]
command = "cp"
args = ["target/release/trisyllabic", "pkg/trisyllabic-linux"]

[tasks.rename-macos]
command = "cp"
args = ["target/release/trisyllabic", "pkg/trisyllabic-macos"]

[tasks.rename]
linux_alias = "rename-linux"
mac_alias = "rename-macos"

[tasks.resources]
command = "cp"
args = ["-r", "resources", "pkg/"]

[tasks.matlab]
command = "cp"
args = ["Trisyllabic.mlapp", "pkg/"]

[tasks.miscellaneous]
command = "cp"
args = ["instructions.txt", "pkg/"]

[tasks.pkg]
dependencies = [
    "clean",
    "prep",
    "build",
    "rename",
    "resources",
    "matlab"
]
